# .github/workflows/file-vault-tracking.yml
name: Create File Vault Issues - Push
on:
  push:
    branches:
      - main
permissions:
  contents: read
  issues: write

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get all modified SLDASM files
        id: modified-assembly-files
        uses: tj-actions/changed-files@v40
        with:
          separator: ","
          files: |
            **.SLDASM

      - name: Split all modified assembly files by delimiter
        id: split
        if: steps.modified-assembly-files.outputs.any_modified == 'true'
        uses: rishabhgupta/split-by@v1
        with:
          string: ${{steps.modified-assembly-files.outputs.all_modified_file}}
          split-by: ","

      - name: List all modified Assembly files
        if: steps.modified-assembly-files.outputs.any_modified == 'true'
        run: |
          for file in ${{steps.split.outputs}}[@]; do
            echo "$file was changed"
          done
